
version: '3.8'

services:

  minecraft-server-example:
    image: itzg/minecraft-server
    container_name: minecraft-server-example
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.20.1"
      MEMORY: "2G"
      SERVER_NAME: "Example Server"
    ports:
      - "25565:25565"
    volumes:
      - ./minecraft_servers/example:/data
    restart: unless-stopped
    
networks:
  default:
    name: minecraft_network
